project:
  type: website
  output-dir: docs

website:
  title: "Notes"
  sidebar:
    collapse-level: 2
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: "DBMS"
        contents:
          - href: pages/DBMS/sql-1.qmd
            text: Introduction to Relational Databases and SQL
          - href: pages/DBMS/sql-2.ipynb
            text: SQL Examples, Intermediate and Advanced SQL
          - href: pages/DBMS/formal-rel-query-lang.qmd
            text: Formal Relational Query Languages
      - section: "PDSA"
        contents:
          # - href: pages/PDSA/w2.qmd
          #   text: Week 2
          - href: pages/PDSA/analysis_of_algorithms.qmd
            text: Analysis of Algorithms
          - href: pages/PDSA/binarysearch.qmd
            text: Binary Search
          - href: pages/PDSA/sorting_algorithms.qmd
            text: Sorting Algorithms
          - href: pages/PDSA/graphs.qmd
            text: Graphs
      - section: "Random Math"
        contents:
          - href: pages/random/Fourier.qmd
            text: Fourier Series Representations
          - href: pages/random/Vectors-in-alternate-basis.qmd
            text: Vectors in Alternate Basis
      - section: "Statistics"
        contents:
          - href: pages/Stats/Probability-Basics.qmd
            text: Basic Concepts of Probability
          # - href: pages/Stats/Prob-Dist-RV.qmd
          #   text: Probability Distributions and Random Variables
  # open-graph: true
            

format:
  html:
    smooth-scroll: true
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    html-math-method: katex
    code-overflow: wrap
