project:
  type: website
  output-dir: docs

website:
  title: "Notes"
  sidebar:
    collapse-level: 2
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: "Statistics"
        contents:
          - href: pages/Stats2/Probability-Basics.qmd
            text: Basic Concepts of Probability
          # - href: pages/Stats2/Prob-Dist-RV.qmd
          #   text: Probability Distributions and Random Variables
      # - section: "DBMS"
      #   contents:
      #     - href: pages/DBMS/w2.qmd
      #       text: Week 2
      #     - href: pages/DBMS/w3.ipynb
      #       text: Week 3
      #     - href: pages/DBMS/w4.qmd
      #       text: Week 4
      - section: "PDSA"
        contents:
          # - href: pages/PDSA/w2.qmd
          #   text: Week 2
          - href: pages/PDSA/analysis_of_algorithms.qmd
            text: Analysis of Algorithms
          - href: pages/PDSA/binarysearch.qmd
            text: Binary Search
          - href: pages/PDSA/sorting_algorithms.qmd
            text: Sorting Algorithms
      # - section: "MAD-2"
      #   contents:
      #     - href: pages/MAD-2/w1.qmd
      #       text: Week 1
      #     - href: pages/MAD-2/w2.qmd
      #       text: Week 2
      #     - href: pages/MAD-2/w3.qmd
      #       text: Week 3
      - section: "Random"
        contents:
          - href: pages/random/Fourier.qmd
            text: Fourier Series Representations
          - href: pages/random/Vectors-in-alternate-basis.qmd
            text: Vectors in Alternate Basis
  # open-graph: true
            

format:
  html:
    smooth-scroll: true
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    html-math-method: katex
    code-overflow: wrap
